language: python
python:
  - "2.7"
  - "3.5"
env:
   - PYTHONPATH=.
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pylint
  - pip install pytest
  - sh ./tests/init_config.sh
# command to run tests
script:
  - flake8 --max-line-length=100 --ignore=F812 matrigram
  - pylint --disable=redefined-builtin,ungrouped-imports,too-many-public-methods,fixme,missing-docstring,invalid-name,protected-access matrigram
  - py.test
